# You also need the Dockerfile_Server file, put it in the same directory as this file.
# Build and create a container with: docker-compose up -d --build
# You may set the version of the server when an update is released, see "args"
#
# Attach to the container with: docker-compose exec lunamultiplayer /bin/ash
version: '3.3'
services:
    lunamultiplayer:
        image: lunamultiplayer:local
        build:
          context: ./
          dockerfile: Dockerfile_Server
        container_name: lunamultiplayer
        environment:
            - TZ=CET
        ports:
            - '8800:8800/udp'
            # uncomment to enable website
            # - '8900:8900'
        volumes:
            - '/opt/LMPServer/Config:/LMPServer/Config'
            - '/opt/LMPServer/Universe:/LMPServer/Universe'
            - '/opt/LMPServer/Plugins:/LMPServer/Plugins'
            - '/opt/LMPServer/logs:/LMPServer/logs'
        restart: unless-stopped
